services:
  redis_db:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - ./blockscout-services-data/redis-data:/data

  db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'blockscout'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./blockscout-services-data/postgres-data:/var/lib/postgresql/data
    ports:
      - 7432:5432

  blockscout:
    depends_on:
      - db
      - redis_db
    image: blockscout/blockscout:${DOCKER_TAG:-6.8.0}
    restart: always
    stop_grace_period: 5m
    container_name: 'blockscout'
    links:
      - db:database
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - ./envs/common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_VARIANT: 'geth'
      ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
      ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545/
      INDEXER_DISABLE_BLOCK_REWARD_FETCHER: 'true'
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'
      DATABASE_URL: postgresql://blockscout:@db:5432/blockscout?ssl=false
      ECTO_USE_SSL: 'false'
      SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
    ports:
      - 4000:4000