version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bloom-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-dev}
      - PORT=3001
    env_file:
      - .env.development
    depends_on: []
    restart: unless-stopped
    networks:
      - bloom-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => { process.exit(1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bloom-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_NODE_ENV=${REACT_APP_NODE_ENV:-dev}
    env_file:
      - ./frontend/.env.development
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - bloom-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bloom-network:
    driver: bridge